name: CI - NestJS with SonarQube

on:
  push:
    branches: [main, develop, 'feature/*', 'bugfix/*']
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker-compose services
        run: docker compose -f docker-compose.yml build

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Wait for SonarQube to be healthy
        shell: bash
        run: |
          echo "⏳ Esperando a SonarQube…"
          for i in {1..15}; do
            status=$(curl -s http://localhost:9000/api/system/health | jq -r .status)
            if [ "$status" = "UP" ]; then
              echo "✅ SonarQube está UP"
              break
            fi
            echo "… status=$status; reintentando en 10s"
            sleep 10
          done

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm test -- --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000
